version: '3.4'
services:
  db:
    image: library/mysql:5.6
    hostname: db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "magento"
    shm_size: '1gb'
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/mysql.cnf
    ports:
      - "3306:3306"
networks:
  default:
    driver: bridge
volumes:
  mysql_data_5.6:
    external: true